# Generated by Django 4.2 on 2023-05-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_source_alter_article_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(null=True, to='articles.genre'),
        ),
    ]
