# Generated by Django 4.2 on 2023-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genres',
            field=models.ManyToManyField(blank=True, to='articles.genre'),
        ),
    ]
