# Generated by Django 4.2 on 2023-05-14 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_comments_article_ratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ratings',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
