services:
  django:
    container_name: news
    image: news
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - django-static:/usr/src/app/staticfiles
      - ./db.sqlite3:/usr/src/app/db.sqlite3
      - ./media:/usr/src/app/media
    depends_on:
      - postgres
    command: python /usr/src/app/manage.py runserver

  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  django-static:
